# JMIR multilingual evidence-selection experiment — main evaluation

Runs the frozen 125-case experiment: 3 languages × 3 evidence conditions × 2 open-weight VLMs = **2250 trials**. Every response is appended immediately to Google Drive. Re-running safely skips completed trial IDs.

Use a **T4 GPU runtime**. Run models sequentially; a second Colab session is neither needed nor recommended.

## 0. Mount Drive, verify the frozen casebook, and create the fixed trial schedule

In [1]:
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
from datetime import datetime, timezone
import base64, hashlib, json, os, random, re, subprocess, time, urllib.request
import pandas as pd

ROOT = Path('/content/drive/MyDrive/Research/6. MedicalVLM_LanguageConflict/JMIR_Evidence_Selection')
CASEBOOK_DIR = ROOT / 'casebooks'
RESULTS = ROOT / 'results' / 'main_evaluation'
RESULTS.mkdir(parents=True, exist_ok=True)

CASEBOOK = CASEBOOK_DIR / 'evaluation_cases_frozen.csv'
HASHFILE = CASEBOOK_DIR / 'evaluation_cases_frozen.csv.sha256'
assert CASEBOOK.exists(), f'Missing: {CASEBOOK}'
assert HASHFILE.exists(), f'Missing: {HASHFILE}'

def sha256_file(path, chunk=1024*1024):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(chunk), b''):
            h.update(block)
    return h.hexdigest()

expected_hash = HASHFILE.read_text(encoding='utf-8').strip().split()[0]
actual_hash = sha256_file(CASEBOOK)
assert actual_hash == expected_hash, f'Frozen casebook hash mismatch: {actual_hash} != {expected_hash}'

cases = pd.read_csv(CASEBOOK, dtype=str, keep_default_na=False).sort_values('case_id').reset_index(drop=True)
assert len(cases) == 125
assert cases['dataset'].value_counts().to_dict() == {'vqa_rad':100, 'slake':25}
assert cases['reference_answer'].value_counts().to_dict() == {'no':63, 'yes':62}
assert cases['case_id'].is_unique and cases['image_key'].is_unique and cases['image_path'].is_unique

SEED = 20260921
LANGUAGES = ['en','id','ms']
CONDITIONS = ['image_only','concordant','conflicting']

schedule = [
    {'case_id':row.case_id, 'language':language, 'condition':condition}
    for _, row in cases.iterrows()
    for language in LANGUAGES
    for condition in CONDITIONS
]
random.Random(SEED).shuffle(schedule)
schedule = pd.DataFrame(schedule)
assert len(schedule) == 1125 and not schedule.duplicated().any()
SCHEDULE = RESULTS / 'fixed_trial_schedule.csv'
schedule_bytes = schedule.to_csv(index=False).encode('utf-8')
schedule_sha = hashlib.sha256(schedule_bytes).hexdigest()
if SCHEDULE.exists() and SCHEDULE.read_bytes() != schedule_bytes:
    raise RuntimeError('Existing trial schedule differs from the fixed protocol schedule.')
SCHEDULE.write_bytes(schedule_bytes)
(RESULTS/'fixed_trial_schedule.csv.sha256').write_text(f'{schedule_sha}  {SCHEDULE.name}\n', encoding='utf-8')

print('Frozen casebook verified:', len(cases), 'cases')
print('Casebook SHA256:', actual_hash)
print('Fixed schedule:', len(schedule), 'trials per model')
print('Schedule SHA256:', schedule_sha)

Mounted at /content/drive
Frozen casebook verified: 125 cases
Casebook SHA256: c1617014f21be02ae1ec78ebb3cf6e862429a88552c0bc25c721b1fa07a9ab46
Fixed schedule: 1125 trials per model
Schedule SHA256: 60c491e1ca05633adc74a21de10d7bda52ce12c9d6db4c613ca5daabdc38c86c

## 1. Confirm the GPU

If this reports no NVIDIA GPU, change the Colab runtime to T4 before continuing.

In [2]:
gpu = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
if gpu.returncode != 0:
    raise RuntimeError('No NVIDIA GPU detected. Select a T4 GPU runtime and reconnect.')
print(gpu.stdout)

Mon Sep 21 15:14:32 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## 2. Install and start Ollama

The asset selector deliberately excludes MLX and chooses the standard Linux AMD64 archive.

In [3]:
import platform, shutil

def find_ollama():
    found = shutil.which('ollama')
    if found: return found
    for p in ['/usr/local/bin/ollama','/usr/bin/ollama']:
        if Path(p).is_file(): return p
    return None

OLLAMA = find_ollama()
if OLLAMA is None:
    request = urllib.request.Request(
        'https://api.github.com/repos/ollama/ollama/releases/latest',
        headers={'User-Agent':'Google-Colab'}
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        release = json.load(response)
    preferred = ['ollama-linux-amd64.tar.zst','ollama-linux-amd64.tgz']
    asset = next((a for name in preferred for a in release.get('assets',[]) if a['name'].lower()==name), None)
    if asset is None:
        names = [a['name'] for a in release.get('assets',[]) if 'linux' in a['name'].lower()]
        raise RuntimeError(f'Standard Linux AMD64 Ollama asset not found. Available: {names}')
    archive = Path('/content') / asset['name']
    print('Ollama release:', release['tag_name'])
    print('Downloading:', asset['name'])
    subprocess.run(['curl','-fL','--retry','5','--retry-delay','5','--connect-timeout','30','-o',str(archive),asset['browser_download_url']], check=True)
    if archive.name.endswith('.tar.zst'):
        subprocess.run(['apt-get','update','-qq'], check=True)
        subprocess.run(['apt-get','install','-y','-qq','zstd'], check=True)
        subprocess.run(['tar','--use-compress-program=unzstd','-xf',str(archive),'-C','/usr'], check=True)
    else:
        subprocess.run(['tar','-xzf',str(archive),'-C','/usr'], check=True)
    OLLAMA = find_ollama()
    if OLLAMA is None:
        hits = subprocess.run(['find','/usr','-type','f','-name','ollama'],capture_output=True,text=True).stdout.splitlines()
        if hits:
            target = Path('/usr/local/bin/ollama')
            if target.exists() or target.is_symlink(): target.unlink()
            target.symlink_to(Path(hits[0]))
            OLLAMA = str(target)
    if OLLAMA is None:
        raise RuntimeError('Ollama archive extracted but executable was not found.')

def ollama_alive():
    try:
        urllib.request.urlopen('http://127.0.0.1:11434/api/tags', timeout=3)
        return True
    except Exception:
        return False

if not ollama_alive():
    ollama_log = open('/content/ollama_server.log','a')
    ollama_process = subprocess.Popen([OLLAMA,'serve'],stdout=ollama_log,stderr=subprocess.STDOUT)
    for _ in range(90):
        if ollama_alive(): break
        time.sleep(1)
if not ollama_alive():
    log = Path('/content/ollama_server.log').read_text(errors='replace')[-3000:]
    raise RuntimeError('Ollama server did not start. Log:\n'+log)
print(subprocess.run([OLLAMA,'--version'],capture_output=True,text=True).stdout.strip())
print('Ollama server ready:', OLLAMA)

Ollama release: v0.34.2
Downloading: ollama-linux-amd64.tar.zst
ollama version is 0.34.2
Ollama server ready: /usr/bin/ollama

## 3. Locked prompts, option counterbalancing, and image resolution

These definitions are identical to the successful pilot. Do not edit them after starting the main run.

In [27]:
QUESTION_COL = {'en':'question_en','id':'question_id','ms':'question_ms'}
PROP_COL = {'en':'proposition_en','id':'proposition_id','ms':'proposition_ms'}
YESNO = {'en':('Yes','No'),'id':('Ya','Tidak'),'ms':('Ya','Tidak')}
INTRO = {
    'en':'Examine the medical image and answer the question.',
    'id':'Periksa gambar medis dan jawab pertanyaannya.',
    'ms':'Periksa imej perubatan dan jawab soalan.'
}
CHOOSE = {
    'en':'Choose exactly one option. Reply with A or B only.',
    'id':'Pilih tepat satu opsi. Jawab hanya dengan A atau B.',
    'ms':'Pilih tepat satu pilihan. Jawab dengan A atau B sahaja.'
}
NOTE = {
    'en':{True:'Clinical note: Evidence of {p} is present.',False:'Clinical note: Evidence of {p} is absent.'},
    'id':{True:'Catatan klinis: Terdapat {p}.',False:'Catatan klinis: Tidak terdapat {p}.'},
    'ms':{True:'Nota klinikal: Terdapat {p}.',False:'Nota klinikal: Tiada {p}.'}
}

def norm_yes(x):
    x = str(x).strip().lower()
    if x in {'yes','ya','true','1'}: return True
    if x in {'no','tidak','false','0'}: return False
    raise ValueError(f'Non-binary reference answer: {x}')

def option_order(case_id, language):
    bit = int(hashlib.sha256(f'{SEED}|{case_id}|{language}'.encode()).hexdigest(),16) % 2
    return ['yes','no'] if bit == 0 else ['no','yes']

def build_prompt(row, language, condition):
    reference_yes = norm_yes(row.reference_answer)
    order = option_order(row.case_id, language)
    yn = {'yes':YESNO[language][0], 'no':YESNO[language][1]}
    parts = [INTRO[language]]
    note_yes = None
    if condition != 'image_only':
        note_yes = reference_yes if condition == 'concordant' else not reference_yes
        parts.append(NOTE[language][note_yes].format(p=row[PROP_COL[language]].strip()))
    parts += [row[QUESTION_COL[language]].strip(), f'A. {yn[order[0]]}\nB. {yn[order[1]]}', CHOOSE[language]]
    correct_letter = 'A' if order[0] == ('yes' if reference_yes else 'no') else 'B'
    note_letter = None if note_yes is None else ('A' if order[0] == ('yes' if note_yes else 'no') else 'B')
    return '\n\n'.join(parts), correct_letter, note_letter, order

def resolve_image(row):
    case_id = row.get("case_id", None)

    if case_id is None or pd.isna(case_id) or not str(case_id).strip():
        case_id = row.name

    case_id = str(case_id).strip()
    dataset = str(row.get("dataset", "")).strip()

    # Ollama-compatible transport copy for the problematic image
    if case_id == "C072":
        safe_path = ROOT / "images" / "vqa_rad" / "C072_ollama_safe.jpg"

        if safe_path.is_file():
            return safe_path

        raise FileNotFoundError(
            f"Normalized C072 image is missing: {safe_path}"
        )

    candidates = []

    recorded_path = row.get("image_path", "")
    if pd.notna(recorded_path) and str(recorded_path).strip():
        recorded_path = Path(str(recorded_path).strip())

        if recorded_path.is_absolute():
            candidates.append(recorded_path)
        else:
            candidates.append(ROOT / recorded_path)

    candidates.extend([
        ROOT / "images" / dataset / f"{case_id}.png",
        ROOT / "images" / dataset / f"{case_id}.jpg",
        ROOT / "images" / dataset / f"{case_id}.jpeg",
    ])

    for path in candidates:
        if path.is_file():
            return path

    raise FileNotFoundError(
        f"Image not found for case_id={case_id}, dataset={dataset}. "
        f"Checked: {[str(path) for path in candidates]}"
    )

for _, row in cases.iterrows(): resolve_image(row)
print('Resolved all',len(cases),'images.')
print('Locked prompt example:\n',build_prompt(cases.iloc[0],'en','conflicting')[0])

Resolved all 125 images.
Locked prompt example:
 Examine the medical image and answer the question.

Clinical note: Evidence of enhancing lesion is absent.

is the lesion enhancing?

A. Yes
B. No

Choose exactly one option. Reply with A or B only.

## 4. Checkpointed inference engine

An `ok` record is never repeated. Error records are retried on the next run. Parse failures remain recorded outcomes rather than being selectively regenerated.

In [28]:
def api_json(path, payload=None, timeout=3600):
    data = None if payload is None else json.dumps(payload).encode('utf-8')
    req = urllib.request.Request('http://127.0.0.1:11434'+path,data=data,headers={'Content-Type':'application/json'})
    with urllib.request.urlopen(req,timeout=timeout) as response:
        return json.loads(response.read())

def model_slug(model): return re.sub(r'[^a-z0-9]+','_',model.lower()).strip('_')
def checkpoint_path(model): return RESULTS/f'main_{model_slug(model)}.jsonl'

def append_jsonl(path,record):
    with open(path,'a',encoding='utf-8') as f:
        f.write(json.dumps(record,ensure_ascii=False)+'\n')
        f.flush(); os.fsync(f.fileno())

def load_records(model):
    path = checkpoint_path(model)
    if not path.exists(): return []
    out=[]
    for i,line in enumerate(path.read_text(encoding='utf-8').splitlines(),1):
        try: out.append(json.loads(line))
        except json.JSONDecodeError: print(f'Ignoring incomplete line {i} in {path.name}')
    return out

def parse_letter(text):
    m = re.search(r'(?<![A-Z])[AB](?![A-Z])',str(text).strip().upper())
    return m.group(0) if m else None

def model_metadata(model):
    info = api_json('/api/show',{'model':model})
    tags = api_json('/api/tags').get('models',[])
    tag = next((x for x in tags if x.get('name')==model or x.get('model')==model),{})
    return {'model':model,'digest':tag.get('digest',''),'details':tag.get('details',{}),'modelfile_sha256':hashlib.sha256(info.get('modelfile','').encode()).hexdigest()}

def trial_id(model,case_id,language,condition): return f'{model}|{case_id}|{language}|{condition}'

def results_table(model):
    rows=load_records(model)
    if not rows: return pd.DataFrame()
    d=pd.DataFrame(rows)
    ok=d[d.status.eq('ok')].drop_duplicates('trial_id',keep='last')
    ok.to_csv(RESULTS/f'main_{model_slug(model)}_latest.csv',index=False)
    return ok

def run_model(model, limit=None, retries=2):
    meta=model_metadata(model)
    prior=load_records(model)
    prior_ok=[r for r in prior if r.get('status')=='ok']
    bad_hash=[r.get('trial_id') for r in prior_ok if r.get('casebook_sha256')!=actual_hash or r.get('schedule_sha256')!=schedule_sha]
    bad_digest=[r.get('trial_id') for r in prior_ok if r.get('model_digest')!=meta['digest']]
    if bad_hash: raise RuntimeError(f'Checkpoint protocol mismatch in {len(bad_hash)} completed trials.')
    if bad_digest: raise RuntimeError(f'Model digest changed; refusing to mix versions ({len(bad_digest)} prior trials).')
    done={r['trial_id'] for r in prior_ok}
    todo=schedule.copy()
    if limit is not None: todo=todo.iloc[:limit]
    case_lookup=cases.set_index('case_id')
    total=len(todo)
    for n,s in enumerate(todo.itertuples(index=False),1):
        row=case_lookup.loc[s.case_id]
        tid=trial_id(model,s.case_id,s.language,s.condition)
        if tid in done:
            print(f'[{n}/{total}] skip {tid}')
            continue
        row = row.copy()
        row["case_id"] = str(s.case_id)
        image_path=resolve_image(row)
        image_b64=base64.b64encode(image_path.read_bytes()).decode('ascii')
        prompt,correct_letter,note_letter,order=build_prompt(row,s.language,s.condition)
        payload={'model':model,'stream':False,'keep_alive':'10m','messages':[{'role':'user','content':prompt,'images':[image_b64]}],'options':{'temperature':0,'seed':SEED,'num_predict':4}}
        for attempt in range(1,retries+2):
            started=time.time()
            try:
                response=api_json('/api/chat',payload)
                raw=response.get('message',{}).get('content','')
                parsed=parse_letter(raw)
                record={
                    'trial_id':tid,'status':'ok','timestamp_utc':datetime.now(timezone.utc).isoformat(),
                    'model':model,'model_digest':meta['digest'],'model_details':meta['details'],
                    'casebook_sha256':actual_hash,'schedule_sha256':schedule_sha,'case_id':s.case_id,
                    'dataset':row.dataset,'language':s.language,'condition':s.condition,
                    'reference_answer':row.reference_answer,'option_a':order[0],'option_b':order[1],
                    'correct_letter':correct_letter,'note_letter':note_letter,'raw_response':raw,
                    'parsed_letter':parsed,'is_correct':None if parsed is None else parsed==correct_letter,
                    'follows_note':None if note_letter is None or parsed is None else parsed==note_letter,
                    'prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),
                    'image_sha256':sha256_file(image_path),'elapsed_seconds':round(time.time()-started,3),
                    'attempt':attempt,'eval_count':response.get('eval_count'),'total_duration_ns':response.get('total_duration')
                }
                append_jsonl(checkpoint_path(model),record); done.add(tid)
                print(f'[{n}/{total}] {tid} -> {raw!r} ({record["elapsed_seconds"]}s)')
                break
            except Exception as e:
                error={'trial_id':tid,'status':'error','timestamp_utc':datetime.now(timezone.utc).isoformat(),'model':model,'case_id':s.case_id,'language':s.language,'condition':s.condition,'attempt':attempt,'error_type':type(e).__name__,'error':str(e),'elapsed_seconds':round(time.time()-started,3)}
                append_jsonl(checkpoint_path(model),error)
                print(f'[{n}/{total}] attempt {attempt} failed: {e}')
                if attempt<=retries: time.sleep(5*attempt)
    return results_table(model)

print('Checkpoint engine ready. Durable directory:',RESULTS)

Checkpoint engine ready. Durable directory: /content/drive/MyDrive/Research/6. MedicalVLM_LanguageConflict/JMIR_Evidence_Selection/results/main_evaluation

## 5. Qwen preflight (18 trials that count toward the main evaluation)

These are the first 18 randomized schedule entries. They remain checkpointed and will be skipped by the full run.

In [16]:
QWEN_MODEL='qwen2.5vl:3b'
subprocess.run([OLLAMA,'pull',QWEN_MODEL],check=True)
print(json.dumps(model_metadata(QWEN_MODEL),indent=2))
qwen_preflight=run_model(QWEN_MODEL,limit=18)
display(qwen_preflight.tail(18)[['case_id','language','condition','raw_response','parsed_letter','is_correct','follows_note','elapsed_seconds']])
print('Qwen completed unique trials:',len(qwen_preflight),'/ 1125')

{
  "model": "qwen2.5vl:3b",
  "digest": "fb90415cde1ef08aa669ae74b082d49b158729b6db1ab183c941417d507e71a1",
  "details": {
    "parent_model": "",
    "format": "gguf",
    "family": "qwen25vl",
    "families": [
      "qwen25vl"
    ],
    "parameter_size": "3.8B",
    "quantization_level": "Q4_K_M",
    "context_length": 128000,
    "embedding_length": 2048
  },
  "modelfile_sha256": "ad0ce6d9b08eafbc4d22401cdbb11d071d700bae66bc3420d9ec45e8e0d0d11e"
}
[1/18] qwen2.5vl:3b|C128|en|concordant -> 'A' (114.646s)
[2/18] qwen2.5vl:3b|C127|id|image_only -> 'A. Ya' (1.367s)
[3/18] qwen2.5vl:3b|C020|ms|concordant -> 'B.' (1.512s)
[4/18] qwen2.5vl:3b|C084|id|conflicting -> 'A.' (1.344s)
[5/18] qwen2.5vl:3b|C065|en|conflicting -> 'B.' (1.317s)
[6/18] qwen2.5vl:3b|C031|id|concordant -> 'A' (2.958s)
[7/18] qwen2.5vl:3b|C067|ms|concordant -> 'B. Tidak' (1.306s)
[8/18] qwen2.5vl:3b|C105|en|image_only -> 'A. No' (1.473s)
[9/18] qwen2.5vl:3b|C031|ms|image_only -> 'B. Ya' (0.211s)
[10/18] qwen2.5vl:3b|C064|en|concordant -> 'B.' (1.5s)
[11/18] qwen2.5vl:3b|C051|ms|concordant -> 'A' (2.047s)
[12/18] qwen2.5vl:3b|C089|ms|image_only -> 'B. Ya' (1.558s)
[13/18] qwen2.5vl:3b|C126|en|conflicting -> 'B' (2.109s)
[14/18] qwen2.5vl:3b|C029|ms|conflicting -> 'A. Ya' (1.306s)
[15/18] qwen2.5vl:3b|C074|en|conflicting -> 'B' (1.28s)
[16/18] qwen2.5vl:3b|C019|id|conflicting -> 'A. Tidak' (1.535s)
[17/18] qwen2.5vl:3b|C015|en|concordant -> 'B.' (2.206s)
[18/18] qwen2.5vl:3b|C042|en|image_only -> 'A.' (1.505s)

,case_id,language,condition,raw_response,parsed_letter,is_correct,follows_note,elapsed_seconds
0,C128,en,concordant,A,A,True,True,114.646
1,C127,id,image_only,A. Ya,A,True,None,1.367
2,C020,ms,concordant,B.,B,True,True,1.512
3,C084,id,conflicting,A.,A,False,True,1.344
4,C065,en,conflicting,B.,B,False,True,1.317
5,C031,id,concordant,A,A,True,True,2.958
6,C067,ms,concordant,B. Tidak,B,True,True,1.306
7,C105,en,image_only,A. No,A,True,None,1.473
8,C031,ms,image_only,B. Ya,B,False,None,0.211
9,C064,en,concordant,B.,B,True,True,1.500
10,C051,ms,concordant,A,A,True,True,2.047
11,C089,ms,image_only,B. Ya,B,False,None,1.558
12,C126,en,conflicting,B,B,False,True,2.109
13,C029,ms,conflicting,A. Ya,A,False,True,1.306
14,C074,en,conflicting,B,B,False,True,1.280
15,C019,id,conflicting,A. Tidak,A,False,True,1.535
16,C015,en,concordant,B.,B,True,True,2.206
17,C042,en,image_only,A.,A,True,None,1.505

Qwen completed unique trials: 18 / 1125

## 6. Run or resume the complete Qwen evaluation

Safe to rerun after interruption.

In [ ]:
from PIL import Image, ImageOps
from pathlib import Path

C072_ORIGINAL = (
    ROOT / "images" / "vqa_rad" / "C072.jpg"
)
C072_SAFE = (
    ROOT / "images" / "vqa_rad" / "C072_ollama_safe.jpg"
)

with Image.open(C072_ORIGINAL) as image:
    image = ImageOps.exif_transpose(image).convert("RGB")

    print("Original dimensions:", image.size)

    # Reduce only if necessary while preserving aspect ratio
    image.thumbnail((1600, 1600), Image.Resampling.LANCZOS)

    image.save(
        C072_SAFE,
        format="JPEG",
        quality=95,
        subsampling=0,
    )

with Image.open(C072_SAFE) as image:
    print("Safe-copy dimensions:", image.size)
    print("Safe-copy mode:", image.mode)
    print("Safe-copy size:", C072_SAFE.stat().st_size, "bytes")
    display(image)

print("Created:", C072_SAFE)

In [29]:
qwen_results=run_model(QWEN_MODEL)
print('Qwen completed unique trials:',len(qwen_results),'/ 1125')
assert len(qwen_results)==1125,'Qwen is incomplete; rerun this cell to retry unfinished/error trials.'
print('Qwen parse failures:',int(qwen_results['parsed_letter'].isna().sum()))

[1/1125] skip qwen2.5vl:3b|C128|en|concordant
[2/1125] skip qwen2.5vl:3b|C127|id|image_only
[3/1125] skip qwen2.5vl:3b|C020|ms|concordant
[4/1125] skip qwen2.5vl:3b|C084|id|conflicting
[5/1125] skip qwen2.5vl:3b|C065|en|conflicting
[6/1125] skip qwen2.5vl:3b|C031|id|concordant
[7/1125] skip qwen2.5vl:3b|C067|ms|concordant
[8/1125] skip qwen2.5vl:3b|C105|en|image_only
[9/1125] skip qwen2.5vl:3b|C031|ms|image_only
[10/1125] skip qwen2.5vl:3b|C064|en|concordant
[11/1125] skip qwen2.5vl:3b|C051|ms|concordant
[12/1125] skip qwen2.5vl:3b|C089|ms|image_only
[13/1125] skip qwen2.5vl:3b|C126|en|conflicting
[14/1125] skip qwen2.5vl:3b|C029|ms|conflicting
[15/1125] skip qwen2.5vl:3b|C074|en|conflicting
[16/1125] skip qwen2.5vl:3b|C019|id|conflicting
[17/1125] skip qwen2.5vl:3b|C015|en|concordant
[18/1125] skip qwen2.5vl:3b|C042|en|image_only
[19/1125] skip qwen2.5vl:3b|C069|id|image_only
[20/1125] skip qwen2.5vl:3b|C114|ms|image_only
[21/1125] skip qwen2.5vl:3b|C068|id|image_only
[22/1125] skip qwen2.5vl:3b|C089|ms|conflicting
[23/1125] skip qwen2.5vl:3b|C118|en|image_only
[24/1125] skip qwen2.5vl:3b|C016|id|conflicting
[25/1125] skip qwen2.5vl:3b|C030|en|conflicting
[26/1125] skip qwen2.5vl:3b|C044|en|image_only
[27/1125] skip qwen2.5vl:3b|C037|id|image_only
[28/1125] skip qwen2.5vl:3b|C084|ms|image_only
[29/1125] skip qwen2.5vl:3b|C026|ms|image_only
[30/1125] skip qwen2.5vl:3b|C041|ms|image_only
[31/1125] skip qwen2.5vl:3b|C091|ms|conflicting
[32/1125] skip qwen2.5vl:3b|C028|en|concordant
[33/1125] skip qwen2.5vl:3b|C037|en|concordant
[34/1125] skip qwen2.5vl:3b|C115|en|conflicting
[35/1125] skip qwen2.5vl:3b|C028|id|conflicting
[36/1125] skip qwen2.5vl:3b|C082|id|conflicting
[37/1125] skip qwen2.5vl:3b|C014|id|concordant
[38/1125] skip qwen2.5vl:3b|C133|en|conflicting
[39/1125] skip qwen2.5vl:3b|C102|ms|image_only
[40/1125] skip qwen2.5vl:3b|C114|id|image_only
[41/1125] skip qwen2.5vl:3b|C037|en|conflicting
[42/1125] skip qwen2.5vl:3b|C024|en|concordant
[43/1125] skip qwen2.5vl:3b|C101|ms|image_only
[44/1125] skip qwen2.5vl:3b|C075|id|conflicting
[45/1125] skip qwen2.5vl:3b|C110|id|image_only
[46/1125] skip qwen2.5vl:3b|C080|ms|image_only
[47/1125] skip qwen2.5vl:3b|C068|en|conflicting
[48/1125] skip qwen2.5vl:3b|C069|id|concordant
[49/1125] skip qwen2.5vl:3b|C047|ms|image_only
[50/1125] skip qwen2.5vl:3b|C027|id|image_only
[51/1125] skip qwen2.5vl:3b|C093|id|conflicting
[52/1125] skip qwen2.5vl:3b|C082|ms|concordant
[53/1125] skip qwen2.5vl:3b|C117|en|concordant
[54/1125] skip qwen2.5vl:3b|C111|id|conflicting
[55/1125] skip qwen2.5vl:3b|C030|ms|image_only
[56/1125] skip qwen2.5vl:3b|C118|en|conflicting
[57/1125] skip qwen2.5vl:3b|C033|en|conflicting
[58/1125] skip qwen2.5vl:3b|C035|en|image_only
[59/1125] skip qwen2.5vl:3b|C085|ms|concordant
[60/1125] skip qwen2.5vl:3b|C047|id|image_only
[61/1125] skip qwen2.5vl:3b|C085|ms|conflicting
[62/1125] skip qwen2.5vl:3b|C088|id|conflicting
[63/1125] skip qwen2.5vl:3b|C085|id|conflicting
[64/1125] skip qwen2.5vl:3b|C060|id|conflicting
[65/1125] skip qwen2.5vl:3b|C048|id|conflicting
[66/1125] skip qwen2.5vl:3b|C099|ms|conflicting
[67/1125] skip qwen2.5vl:3b|C061|ms|image_only
[68/1125] skip qwen2.5vl:3b|C093|en|conflicting
[69/1125] skip qwen2.5vl:3b|C051|en|concordant
[70/1125] skip qwen2.5vl:3b|C068|ms|concordant
[71/1125] skip qwen2.5vl:3b|C011|en|concordant
[72/1125] skip qwen2.5vl:3b|C021|id|conflicting
[73/1125] skip qwen2.5vl:3b|C110|id|concordant
[74/1125] skip qwen2.5vl:3b|C043|ms|concordant
[75/1125] skip qwen2.5vl:3b|C041|en|image_only
[76/1125] skip qwen2.5vl:3b|C089|ms|concordant
[77/1125] skip qwen2.5vl:3b|C115|id|conflicting
[78/1125] skip qwen2.5vl:3b|C055|ms|concordant
[79/1125] skip qwen2.5vl:3b|C073|ms|concordant
[80/1125] skip qwen2.5vl:3b|C085|en|conflicting
[81/1125] skip qwen2.5vl:3b|C082|en|concordant
[82/1125] skip qwen2.5vl:3b|C108|id|concordant
[83/1125] skip qwen2.5vl:3b|C056|en|conflicting
[84/1125] skip qwen2.5vl:3b|C119|ms|conflicting
[85/1125] skip qwen2.5vl:3b|C124|ms|concordant
[86/1125] skip qwen2.5vl:3b|C119|id|concordant
[87/1125] skip qwen2.5vl:3b|C052|ms|conflicting
[88/1125] skip qwen2.5vl:3b|C098|id|concordant
[89/1125] skip qwen2.5vl:3b|C088|en|conflicting
[90/1125] skip qwen2.5vl:3b|C054|en|concordant
[91/1125] skip qwen2.5vl:3b|C044|ms|conflicting
[92/1125] skip qwen2.5vl:3b|C032|ms|conflicting
[93/1125] skip qwen2.5vl:3b|C030|id|concordant
[94/1125] skip qwen2.5vl:3b|C043|ms|conflicting
[95/1125] skip qwen2.5vl:3b|C045|id|image_only
[96/1125] skip qwen2.5vl:3b|C053|id|concordant
[97/1125] skip qwen2.5vl:3b|C033|ms|concordant
[98/1125] skip qwen2.5vl:3b|C128|ms|conflicting
[99/1125] skip qwen2.5vl:3b|C096|id|conflicting
[100/1125] skip qwen2.5vl:3b|C078|ms|concordant
[101/1125] skip qwen2.5vl:3b|C043|ms|image_only
[102/1125] skip qwen2.5vl:3b|C130|ms|conflicting
[103/1125] skip qwen2.5vl:3b|C125|id|image_only
[104/1125] skip qwen2.5vl:3b|C042|ms|concordant
[105/1125] skip qwen2.5vl:3b|C071|ms|image_only
[106/1125] skip qwen2.5vl:3b|C012|en|conflicting
[107/1125] skip qwen2.5vl:3b|C059|ms|conflicting
[108/1125] skip qwen2.5vl:3b|C033|id|image_only
[109/1125] skip qwen2.5vl:3b|C012|ms|conflicting
[110/1125] skip qwen2.5vl:3b|C067|id|image_only
[111/1125] skip qwen2.5vl:3b|C126|ms|image_only
[112/1125] skip qwen2.5vl:3b|C013|ms|image_only
[113/1125] skip qwen2.5vl:3b|C044|id|concordant
[114/1125] skip qwen2.5vl:3b|C055|ms|conflicting
[115/1125] skip qwen2.5vl:3b|C017|ms|image_only
[116/1125] skip qwen2.5vl:3b|C132|id|concordant
[117/1125] skip qwen2.5vl:3b|C109|en|conflicting
[118/1125] skip qwen2.5vl:3b|C049|id|concordant
[119/1125] skip qwen2.5vl:3b|C100|ms|concordant
[120/1125] skip qwen2.5vl:3b|C012|en|concordant
[121/1125] skip qwen2.5vl:3b|C022|id|concordant
[122/1125] skip qwen2.5vl:3b|C122|ms|conflicting
[123/1125] skip qwen2.5vl:3b|C126|en|concordant
[124/1125] skip qwen2.5vl:3b|C113|ms|image_only
[125/1125] skip qwen2.5vl:3b|C075|en|conflicting
[126/1125] skip qwen2.5vl:3b|C089|id|concordant
[127/1125] skip qwen2.5vl:3b|C094|id|image_only
[128/1125] skip qwen2.5vl:3b|C128|en|image_only
[129/1125] skip qwen2.5vl:3b|C049|en|concordant
[130/1125] skip qwen2.5vl:3b|C104|ms|concordant
[131/1125] skip qwen2.5vl:3b|C115|id|image_only
[132/1125] skip qwen2.5vl:3b|C068|en|image_only
[133/1125] skip qwen2.5vl:3b|C017|ms|concordant
[134/1125] skip qwen2.5vl:3b|C014|id|conflicting
[135/1125] skip qwen2.5vl:3b|C076|ms|conflicting
[136/1125] skip qwen2.5vl:3b|C124|id|conflicting
[137/1125] skip qwen2.5vl:3b|C131|id|concordant
[138/1125] skip qwen2.5vl:3b|C110|en|concordant
[139/1125] skip qwen2.5vl:3b|C115|en|concordant
[140/1125] skip qwen2.5vl:3b|C073|id|concordant
[141/1125] skip qwen2.5vl:3b|C090|ms|concordant
[142/1125] skip qwen2.5vl:3b|C051|id|concordant
[143/1125] skip qwen2.5vl:3b|C027|ms|concordant
[144/1125] skip qwen2.5vl:3b|C032|en|conflicting
[145/1125] skip qwen2.5vl:3b|C111|en|image_only
[146/1125] skip qwen2.5vl:3b|C062|id|image_only
[147/1125] skip qwen2.5vl:3b|C050|ms|image_only
[148/1125] skip qwen2.5vl:3b|C069|id|conflicting
[149/1125] skip qwen2.5vl:3b|C025|id|conflicting
[150/1125] skip qwen2.5vl:3b|C016|id|concordant
[151/1125] skip qwen2.5vl:3b|C116|id|concordant
[152/1125] skip qwen2.5vl:3b|C052|en|image_only
[153/1125] skip qwen2.5vl:3b|C097|id|concordant
[154/1125] skip qwen2.5vl:3b|C022|id|image_only
[155/1125] skip qwen2.5vl:3b|C032|ms|image_only
[156/1125] skip qwen2.5vl:3b|C038|id|conflicting
[157/1125] skip qwen2.5vl:3b|C134|en|image_only
[158/1125] skip qwen2.5vl:3b|C099|en|concordant
[159/1125] skip qwen2.5vl:3b|C034|en|concordant
[160/1125] qwen2.5vl:3b|C072|id|conflicting -> 'A' (3.372s)
[161/1125] skip qwen2.5vl:3b|C088|ms|image_only
[162/1125] skip qwen2.5vl:3b|C120|en|image_only
[163/1125] skip qwen2.5vl:3b|C051|en|conflicting
[164/1125] skip qwen2.5vl:3b|C047|en|concordant
[165/1125] skip qwen2.5vl:3b|C117|id|conflicting
[166/1125] skip qwen2.5vl:3b|C094|ms|image_only
[167/1125] skip qwen2.5vl:3b|C038|en|conflicting
[168/1125] skip qwen2.5vl:3b|C013|ms|concordant
[169/1125] skip qwen2.5vl:3b|C119|en|conflicting
[170/1125] skip qwen2.5vl:3b|C020|id|conflicting
[171/1125] skip qwen2.5vl:3b|C119|en|image_only
[172/1125] skip qwen2.5vl:3b|C082|ms|image_only
[173/1125] skip qwen2.5vl:3b|C059|en|conflicting
[174/1125] skip qwen2.5vl:3b|C090|ms|conflicting
[175/1125] skip qwen2.5vl:3b|C034|en|image_only
[176/1125] skip qwen2.5vl:3b|C082|en|image_only
[177/1125] skip qwen2.5vl:3b|C073|ms|image_only
[178/1125] skip qwen2.5vl:3b|C032|id|concordant
[179/1125] skip qwen2.5vl:3b|C027|en|concordant
[180/1125] skip qwen2.5vl:3b|C022|ms|image_only
[181/1125] skip qwen2.5vl:3b|C088|ms|concordant
[182/1125] skip qwen2.5vl:3b|C017|id|conflicting
[183/1125] skip qwen2.5vl:3b|C125|en|concordant
[184/1125] skip qwen2.5vl:3b|C087|ms|image_only
[185/1125] skip qwen2.5vl:3b|C080|id|concordant
[186/1125] skip qwen2.5vl:3b|C129|en|conflicting
[187/1125] skip qwen2.5vl:3b|C064|id|image_only
[188/1125] skip qwen2.5vl:3b|C087|en|conflicting
[189/1125] skip qwen2.5vl:3b|C096|id|image_only
[190/1125] skip qwen2.5vl:3b|C115|ms|concordant
[191/1125] skip qwen2.5vl:3b|C015|en|image_only
[192/1125] skip qwen2.5vl:3b|C104|en|concordant
[193/1125] skip qwen2.5vl:3b|C059|id|concordant
[194/1125] skip qwen2.5vl:3b|C024|ms|conflicting
[195/1125] skip qwen2.5vl:3b|C109|en|concordant
[196/1125] skip qwen2.5vl:3b|C042|id|conflicting
[197/1125] skip qwen2.5vl:3b|C042|ms|image_only
[198/1125] skip qwen2.5vl:3b|C129|en|concordant
[199/1125] skip qwen2.5vl:3b|C011|id|conflicting
[200/1125] skip qwen2.5vl:3b|C061|id|conflicting
[201/1125] skip qwen2.5vl:3b|C047|en|image_only
[202/1125] skip qwen2.5vl:3b|C090|ms|image_only
[203/1125] skip qwen2.5vl:3b|C073|en|image_only
[204/1125] skip qwen2.5vl:3b|C047|ms|conflicting
[205/1125] skip qwen2.5vl:3b|C056|ms|conflicting
[206/1125] skip qwen2.5vl:3b|C051|en|image_only
[207/1125] skip qwen2.5vl:3b|C094|id|concordant
[208/1125] skip qwen2.5vl:3b|C053|en|concordant
[209/1125] skip qwen2.5vl:3b|C126|id|concordant
[210/1125] skip qwen2.5vl:3b|C070|id|image_only
[211/1125] skip qwen2.5vl:3b|C012|id|conflicting
[212/1125] skip qwen2.5vl:3b|C036|id|concordant
[213/1125] skip qwen2.5vl:3b|C079|id|conflicting
[214/1125] skip qwen2.5vl:3b|C051|ms|image_only
[215/1125] skip qwen2.5vl:3b|C124|en|concordant
[216/1125] skip qwen2.5vl:3b|C016|en|conflicting
[217/1125] skip qwen2.5vl:3b|C030|ms|concordant
[218/1125] skip qwen2.5vl:3b|C110|en|conflicting
[219/1125] skip qwen2.5vl:3b|C119|ms|image_only
[220/1125] skip qwen2.5vl:3b|C063|id|conflicting
[221/1125] skip qwen2.5vl:3b|C103|id|conflicting
[222/1125] skip qwen2.5vl:3b|C025|id|image_only
[223/1125] skip qwen2.5vl:3b|C050|id|image_only
[224/1125] skip qwen2.5vl:3b|C059|ms|concordant
[225/1125] skip qwen2.5vl:3b|C120|id|conflicting
[226/1125] skip qwen2.5vl:3b|C022|en|image_only
[227/1125] skip qwen2.5vl:3b|C048|en|image_only
[228/1125] skip qwen2.5vl:3b|C053|en|conflicting
[229/1125] skip qwen2.5vl:3b|C081|id|image_only
[230/1125] skip qwen2.5vl:3b|C125|ms|concordant
[231/1125] skip qwen2.5vl:3b|C065|en|concordant
[232/1125] skip qwen2.5vl:3b|C077|en|concordant
[233/1125] skip qwen2.5vl:3b|C109|id|concordant
[234/1125] skip qwen2.5vl:3b|C135|ms|image_only
[235/1125] skip qwen2.5vl:3b|C036|ms|conflicting
[236/1125] skip qwen2.5vl:3b|C023|ms|image_only
[237/1125] skip qwen2.5vl:3b|C024|id|concordant
[238/1125] skip qwen2.5vl:3b|C075|en|image_only
[239/1125] skip qwen2.5vl:3b|C118|en|concordant
[240/1125] skip qwen2.5vl:3b|C049|id|image_only
[241/1125] skip qwen2.5vl:3b|C020|ms|conflicting
[242/1125] skip qwen2.5vl:3b|C083|ms|conflicting
[243/1125] skip qwen2.5vl:3b|C079|id|concordant
[244/1125] skip qwen2.5vl:3b|C109|ms|concordant
[245/1125] skip qwen2.5vl:3b|C016|ms|conflicting
[246/1125] skip qwen2.5vl:3b|C135|en|concordant
[247/1125] skip qwen2.5vl:3b|C069|ms|concordant
[248/1125] skip qwen2.5vl:3b|C037|id|conflicting
[249/1125] skip qwen2.5vl:3b|C074|en|concordant
[250/1125] skip qwen2.5vl:3b|C054|ms|concordant
[251/1125] skip qwen2.5vl:3b|C061|ms|concordant
[252/1125] skip qwen2.5vl:3b|C122|id|conflicting
[253/1125] skip qwen2.5vl:3b|C097|ms|concordant
[254/1125] skip qwen2.5vl:3b|C036|ms|image_only
[255/1125] skip qwen2.5vl:3b|C011|ms|conflicting
[256/1125] qwen2.5vl:3b|C072|id|concordant -> 'B.' (0.227s)
[257/1125] skip qwen2.5vl:3b|C060|en|conflicting
[258/1125] skip qwen2.5vl:3b|C135|ms|concordant
[259/1125] skip qwen2.5vl:3b|C054|id|concordant
[260/1125] skip qwen2.5vl:3b|C131|ms|concordant
[261/1125] skip qwen2.5vl:3b|C067|id|concordant
[262/1125] skip qwen2.5vl:3b|C096|id|concordant
[263/1125] skip qwen2.5vl:3b|C091|en|conflicting
[264/1125] skip qwen2.5vl:3b|C050|ms|concordant
[265/1125] skip qwen2.5vl:3b|C120|id|image_only
[266/1125] skip qwen2.5vl:3b|C028|id|image_only
[267/1125] skip qwen2.5vl:3b|C120|id|concordant
[268/1125] skip qwen2.5vl:3b|C103|en|concordant
[269/1125] skip qwen2.5vl:3b|C025|en|conflicting
[270/1125] skip qwen2.5vl:3b|C080|en|conflicting
[271/1125] skip qwen2.5vl:3b|C130|en|concordant
[272/1125] skip qwen2.5vl:3b|C109|ms|conflicting
[273/1125] skip qwen2.5vl:3b|C085|id|concordant
[274/1125] skip qwen2.5vl:3b|C062|ms|conflicting
[275/1125] skip qwen2.5vl:3b|C022|ms|concordant
[276/1125] skip qwen2.5vl:3b|C027|en|conflicting
[277/1125] skip qwen2.5vl:3b|C097|id|conflicting
[278/1125] skip qwen2.5vl:3b|C077|id|conflicting
[279/1125] skip qwen2.5vl:3b|C135|en|conflicting
[280/1125] skip qwen2.5vl:3b|C132|ms|image_only
[281/1125] skip qwen2.5vl:3b|C084|en|conflicting
[282/1125] skip qwen2.5vl:3b|C023|id|concordant
[283/1125] skip qwen2.5vl:3b|C074|id|image_only
[284/1125] skip qwen2.5vl:3b|C108|ms|concordant
[285/1125] skip qwen2.5vl:3b|C061|ms|conflicting
[286/1125] skip qwen2.5vl:3b|C116|en|conflicting
[287/1125] skip qwen2.5vl:3b|C012|id|concordant
[288/1125] skip qwen2.5vl:3b|C132|id|image_only
[289/1125] skip qwen2.5vl:3b|C052|en|concordant
[290/1125] skip qwen2.5vl:3b|C113|ms|conflicting
[291/1125] skip qwen2.5vl:3b|C111|ms|image_only
[292/1125] skip qwen2.5vl:3b|C061|en|image_only
[293/1125] skip qwen2.5vl:3b|C083|en|concordant
[294/1125] skip qwen2.5vl:3b|C053|id|image_only
[295/1125] skip qwen2.5vl:3b|C092|id|concordant
[296/1125] skip qwen2.5vl:3b|C092|en|conflicting
[297/1125] skip qwen2.5vl:3b|C096|ms|concordant
[298/1125] skip qwen2.5vl:3b|C102|id|conflicting
[299/1125] skip qwen2.5vl:3b|C080|ms|concordant
[300/1125] skip qwen2.5vl:3b|C029|id|conflicting
[301/1125] skip qwen2.5vl:3b|C099|ms|concordant
[302/1125] skip qwen2.5vl:3b|C022|en|conflicting
[303/1125] skip qwen2.5vl:3b|C066|id|concordant
[304/1125] skip qwen2.5vl:3b|C116|ms|conflicting
[305/1125] skip qwen2.5vl:3b|C063|en|conflicting
[306/1125] skip qwen2.5vl:3b|C058|id|concordant
[307/1125] skip qwen2.5vl:3b|C103|id|concordant
[308/1125] skip qwen2.5vl:3b|C052|id|image_only
[309/1125] skip qwen2.5vl:3b|C120|ms|image_only
[310/1125] skip qwen2.5vl:3b|C050|id|conflicting
[311/1125] skip qwen2.5vl:3b|C012|id|image_only
[312/1125] skip qwen2.5vl:3b|C114|id|conflicting
[313/1125] skip qwen2.5vl:3b|C062|id|concordant
[314/1125] skip qwen2.5vl:3b|C099|id|image_only
[315/1125] skip qwen2.5vl:3b|C047|en|conflicting
[316/1125] skip qwen2.5vl:3b|C084|ms|conflicting
[317/1125] skip qwen2.5vl:3b|C108|id|conflicting
[318/1125] skip qwen2.5vl:3b|C124|ms|image_only
[319/1125] skip qwen2.5vl:3b|C102|id|concordant
[320/1125] skip qwen2.5vl:3b|C119|id|conflicting
[321/1125] skip qwen2.5vl:3b|C065|id|concordant
[322/1125] skip qwen2.5vl:3b|C120|ms|conflicting
[323/1125] skip qwen2.5vl:3b|C061|en|conflicting
[324/1125] skip qwen2.5vl:3b|C079|en|concordant
[325/1125] skip qwen2.5vl:3b|C068|id|concordant
[326/1125] skip qwen2.5vl:3b|C099|id|conflicting
[327/1125] skip qwen2.5vl:3b|C034|ms|image_only
[328/1125] skip qwen2.5vl:3b|C036|ms|concordant
[329/1125] skip qwen2.5vl:3b|C113|id|image_only
[330/1125] skip qwen2.5vl:3b|C121|id|concordant
[331/1125] skip qwen2.5vl:3b|C014|ms|image_only
[332/1125] skip qwen2.5vl:3b|C044|id|conflicting
[333/1125] skip qwen2.5vl:3b|C099|en|conflicting
[334/1125] skip qwen2.5vl:3b|C031|id|conflicting
[335/1125] skip qwen2.5vl:3b|C044|en|conflicting
[336/1125] skip qwen2.5vl:3b|C031|id|image_only
[337/1125] skip qwen2.5vl:3b|C044|en|concordant
[338/1125] skip qwen2.5vl:3b|C041|ms|conflicting
[339/1125] skip qwen2.5vl:3b|C071|ms|conflicting
[340/1125] skip qwen2.5vl:3b|C082|ms|conflicting
[341/1125] skip qwen2.5vl:3b|C103|en|image_only
[342/1125] skip qwen2.5vl:3b|C127|en|image_only
[343/1125] skip qwen2.5vl:3b|C118|ms|conflicting
[344/1125] skip qwen2.5vl:3b|C081|en|concordant
[345/1125] skip qwen2.5vl:3b|C101|id|image_only
[346/1125] skip qwen2.5vl:3b|C079|id|image_only
[347/1125] skip qwen2.5vl:3b|C070|en|concordant
[348/1125] skip qwen2.5vl:3b|C122|id|concordant
[349/1125] skip qwen2.5vl:3b|C105|en|concordant
[350/1125] skip qwen2.5vl:3b|C046|en|image_only
[351/1125] skip qwen2.5vl:3b|C066|ms|conflicting
[352/1125] skip qwen2.5vl:3b|C011|en|conflicting
[353/1125] skip qwen2.5vl:3b|C112|ms|conflicting
[354/1125] skip qwen2.5vl:3b|C015|ms|conflicting
[355/1125] skip qwen2.5vl:3b|C063|ms|conflicting
[356/1125] skip qwen2.5vl:3b|C024|ms|concordant
[357/1125] skip qwen2.5vl:3b|C020|id|image_only
[358/1125] skip qwen2.5vl:3b|C026|ms|conflicting
[359/1125] skip qwen2.5vl:3b|C111|id|image_only
[360/1125] skip qwen2.5vl:3b|C049|en|image_only
[361/1125] skip qwen2.5vl:3b|C041|en|conflicting
[362/1125] skip qwen2.5vl:3b|C034|en|conflicting
[363/1125] skip qwen2.5vl:3b|C042|ms|conflicting
[364/1125] skip qwen2.5vl:3b|C039|ms|conflicting
[365/1125] skip qwen2.5vl:3b|C021|en|conflicting
[366/1125] skip qwen2.5vl:3b|C128|id|image_only
[367/1125] skip qwen2.5vl:3b|C093|ms|conflicting
[368/1125] skip qwen2.5vl:3b|C064|id|conflicting
[369/1125] skip qwen2.5vl:3b|C126|en|image_only
[370/1125] skip qwen2.5vl:3b|C026|en|image_only
[371/1125] skip qwen2.5vl:3b|C083|en|image_only
[372/1125] skip qwen2.5vl:3b|C047|id|concordant
[373/1125] skip qwen2.5vl:3b|C058|id|image_only
[374/1125] skip qwen2.5vl:3b|C086|id|concordant
[375/1125] skip qwen2.5vl:3b|C081|ms|concordant
[376/1125] skip qwen2.5vl:3b|C026|en|concordant
[377/1125] skip qwen2.5vl:3b|C135|id|image_only
[378/1125] skip qwen2.5vl:3b|C055|id|conflicting
[379/1125] skip qwen2.5vl:3b|C130|ms|concordant
[380/1125] skip qwen2.5vl:3b|C102|id|image_only
[381/1125] skip qwen2.5vl:3b|C131|id|conflicting
[382/1125] skip qwen2.5vl:3b|C031|ms|conflicting
[383/1125] skip qwen2.5vl:3b|C035|ms|concordant
[384/1125] skip qwen2.5vl:3b|C128|id|concordant
[385/1125] skip qwen2.5vl:3b|C061|id|concordant
[386/1125] skip qwen2.5vl:3b|C037|ms|concordant
[387/1125] skip qwen2.5vl:3b|C050|id|concordant
[388/1125] skip qwen2.5vl:3b|C125|id|conflicting
[389/1125] skip qwen2.5vl:3b|C129|id|concordant
[390/1125] skip qwen2.5vl:3b|C019|id|concordant
[391/1125] skip qwen2.5vl:3b|C052|id|concordant
[392/1125] skip qwen2.5vl:3b|C026|id|image_only
[393/1125] skip qwen2.5vl:3b|C088|id|image_only
[394/1125] skip qwen2.5vl:3b|C055|ms|image_only
[395/1125] skip qwen2.5vl:3b|C050|en|conflicting
[396/1125] skip qwen2.5vl:3b|C043|id|conflicting
[397/1125] skip qwen2.5vl:3b|C113|ms|concordant
[398/1125] skip qwen2.5vl:3b|C132|ms|concordant
[399/1125] skip qwen2.5vl:3b|C090|en|image_only
[400/1125] skip qwen2.5vl:3b|C084|id|concordant
[401/1125] skip qwen2.5vl:3b|C121|en|image_only
[402/1125] skip qwen2.5vl:3b|C038|id|concordant
[403/1125] skip qwen2.5vl:3b|C064|en|conflicting
[404/1125] skip qwen2.5vl:3b|C025|id|concordant
[405/1125] skip qwen2.5vl:3b|C112|ms|image_only
[406/1125] skip qwen2.5vl:3b|C040|id|conflicting
[407/1125] skip qwen2.5vl:3b|C051|id|conflicting
[408/1125] skip qwen2.5vl:3b|C083|id|image_only
[409/1125] skip qwen2.5vl:3b|C114|en|conflicting
[410/1125] skip qwen2.5vl:3b|C048|ms|conflicting
[411/1125] skip qwen2.5vl:3b|C065|en|image_only
[412/1125] skip qwen2.5vl:3b|C106|id|concordant
[413/1125] qwen2.5vl:3b|C072|id|image_only -> 'B. Ya' (0.232s)
[414/1125] skip qwen2.5vl:3b|C059|en|concordant
[415/1125] skip qwen2.5vl:3b|C122|ms|concordant

### TroubleShooting

In [ ]:
# Find the 1125-row trial schedule automatically
schedule_candidates = []

for name, obj in globals().items():
    if (
        isinstance(obj, pd.DataFrame)
        and len(obj) == 1125
        and {"case_id", "language", "condition"}.issubset(obj.columns)
    ):
        schedule_candidates.append((name, obj))

print("Schedule candidates:", [name for name, _ in schedule_candidates])

if not schedule_candidates:
    raise RuntimeError(
        "Could not locate the 1125-row schedule. "
        "Please show the output of: print(list(globals().keys()))"
    )

schedule_name, expected_trials = schedule_candidates[0]
expected_trials = expected_trials[
    ["case_id", "language", "condition"]
].astype(str).drop_duplicates()

completed_trials = qwen_results[
    ["case_id", "language", "condition"]
].astype(str).drop_duplicates()

missing_trials = (
    expected_trials.merge(
        completed_trials,
        on=["case_id", "language", "condition"],
        how="left",
        indicator=True,
    )
    .query('_merge == "left_only"')
    .drop(columns="_merge")
    .sort_values(["case_id", "language", "condition"])
)

print("Schedule used:", schedule_name)
print("Missing trials:", len(missing_trials))
display(missing_trials)

print("\nMissing trials per case:")
display(
    missing_trials.groupby("case_id")
    .size()
    .rename("missing_count")
    .reset_index()
)

In [23]:
print("Possible Qwen/checkpoint variables:")

for name, value in list(globals().items()):
    lowered = name.lower()

    if "qwen" in lowered or "checkpoint" in lowered or lowered.endswith("_cp"):
        if isinstance(value, (str, Path)):
            print(name, "=", value)

Possible Qwen/checkpoint variables:
QWEN_MODEL = qwen2.5vl:3b

In [ ]:
import json
from pathlib import Path

print("Searching JSONL checkpoints for C072 errors...\n")

found = 0

for path in ROOT.rglob("*.jsonl"):
    try:
        with path.open("r", encoding="utf-8") as file:
            for line_number, line in enumerate(file, start=1):
                if "C072" not in line:
                    continue

                try:
                    record = json.loads(line)
                except Exception:
                    continue

                if record.get("status") == "error":
                    found += 1
                    print("FILE:", path)
                    print("LINE:", line_number)
                    print(json.dumps(record, indent=2, ensure_ascii=False))
                    print()
    except Exception:
        pass

print("C072 error records found:", found)

In [ ]:
from PIL import Image

c072_rows = []

for name, obj in list(globals().items()):
    if not isinstance(obj, pd.DataFrame):
        continue

    if "case_id" in obj.columns:
        matched = obj[obj["case_id"].astype(str).eq("C072")]
        if len(matched):
            c072_rows.append((name, matched.iloc[0]))

    elif obj.index.name == "case_id" and "C072" in obj.index.astype(str):
        c072_rows.append((name, obj.loc["C072"]))

print("Dataframes containing C072:", [name for name, _ in c072_rows])

if not c072_rows:
    raise RuntimeError("Could not locate C072 in an active dataframe.")

source_name, c072_row = c072_rows[0]
c072_row = c072_row.copy()
c072_row["case_id"] = "C072"

c072_path = resolve_image(c072_row)

print("Source dataframe:", source_name)
print("Image path:", c072_path)
print("File size:", c072_path.stat().st_size, "bytes")

with Image.open(c072_path) as image:
    print("Format:", image.format)
    print("Mode:", image.mode)
    print("Dimensions:", image.size)
    image.verify()

print("Pillow verification: PASSED")
display(Image.open(c072_path))

## 7. Unload Qwen and run Gemma preflight

In [30]:
try: api_json('/api/generate',{'model':QWEN_MODEL,'keep_alive':0})
except Exception as e: print('Unload note:',e)
GEMMA_MODEL='gemma3:4b'
subprocess.run([OLLAMA,'pull',GEMMA_MODEL],check=True)
print(json.dumps(model_metadata(GEMMA_MODEL),indent=2))
gemma_preflight=run_model(GEMMA_MODEL,limit=18)
display(gemma_preflight.tail(18)[['case_id','language','condition','raw_response','parsed_letter','is_correct','follows_note','elapsed_seconds']])
print('Gemma completed unique trials:',len(gemma_preflight),'/ 1125')

{
  "model": "gemma3:4b",
  "digest": "a2af6cc3eb7fa8be8504abaf9b04e88f17a119ec3f04a3addf55f92841195f5a",
  "details": {
    "parent_model": "",
    "format": "gguf",
    "family": "gemma3",
    "families": [
      "gemma3"
    ],
    "parameter_size": "4.3B",
    "quantization_level": "Q4_K_M",
    "context_length": 131072,
    "embedding_length": 2560
  },
  "modelfile_sha256": "5e30e95594473dde0d7779928fee0de00266fd86934b65645af7e93fe83b9fda"
}
[1/18] gemma3:4b|C128|en|concordant -> 'A\n' (55.509s)
[2/18] gemma3:4b|C127|id|image_only -> 'A\n' (1.428s)
[3/18] gemma3:4b|C020|ms|concordant -> 'B. Tidak\n' (1.399s)
[4/18] gemma3:4b|C084|id|conflicting -> 'A\n' (1.38s)
[5/18] gemma3:4b|C065|en|conflicting -> 'B' (1.364s)
[6/18] gemma3:4b|C031|id|concordant -> 'A\n' (1.415s)
[7/18] gemma3:4b|C067|ms|concordant -> 'B\n' (1.387s)
[8/18] gemma3:4b|C105|en|image_only -> 'B\n' (1.357s)
[9/18] gemma3:4b|C031|ms|image_only -> 'B. Ya' (1.454s)
[10/18] gemma3:4b|C064|en|concordant -> 'B' (1.402s)
[11/18] gemma3:4b|C051|ms|concordant -> 'A. Tidak\n' (1.472s)
[12/18] gemma3:4b|C089|ms|image_only -> 'B' (1.415s)
[13/18] gemma3:4b|C126|en|conflicting -> 'B\n' (1.414s)
[14/18] gemma3:4b|C029|ms|conflicting -> 'A. Ya' (1.408s)
[15/18] gemma3:4b|C074|en|conflicting -> 'B\n' (1.381s)
[16/18] gemma3:4b|C019|id|conflicting -> 'A\n' (1.404s)
[17/18] gemma3:4b|C015|en|concordant -> 'B\n' (1.411s)
[18/18] gemma3:4b|C042|en|image_only -> 'A' (1.362s)

,case_id,language,condition,raw_response,parsed_letter,is_correct,follows_note,elapsed_seconds
0,C128,en,concordant,A\n,A,True,True,55.509
1,C127,id,image_only,A\n,A,True,None,1.428
2,C020,ms,concordant,B. Tidak\n,B,True,True,1.399
3,C084,id,conflicting,A\n,A,False,True,1.380
4,C065,en,conflicting,B,B,False,True,1.364
5,C031,id,concordant,A\n,A,True,True,1.415
6,C067,ms,concordant,B\n,B,True,True,1.387
7,C105,en,image_only,B\n,B,False,None,1.357
8,C031,ms,image_only,B. Ya,B,False,None,1.454
9,C064,en,concordant,B,B,True,True,1.402
10,C051,ms,concordant,A. Tidak\n,A,True,True,1.472
11,C089,ms,image_only,B,B,False,None,1.415
12,C126,en,conflicting,B\n,B,False,True,1.414
13,C029,ms,conflicting,A. Ya,A,False,True,1.408
14,C074,en,conflicting,B\n,B,False,True,1.381
15,C019,id,conflicting,A\n,A,False,True,1.404
16,C015,en,concordant,B\n,B,True,True,1.411
17,C042,en,image_only,A,A,True,None,1.362

Gemma completed unique trials: 18 / 1125

## 8. Run or resume the complete Gemma evaluation

In [31]:
gemma_results=run_model(GEMMA_MODEL)
print('Gemma completed unique trials:',len(gemma_results),'/ 1125')
assert len(gemma_results)==1125,'Gemma is incomplete; rerun this cell to retry unfinished/error trials.'
print('Gemma parse failures:',int(gemma_results['parsed_letter'].isna().sum()))

[1/1125] skip gemma3:4b|C128|en|concordant
[2/1125] skip gemma3:4b|C127|id|image_only
[3/1125] skip gemma3:4b|C020|ms|concordant
[4/1125] skip gemma3:4b|C084|id|conflicting
[5/1125] skip gemma3:4b|C065|en|conflicting
[6/1125] skip gemma3:4b|C031|id|concordant
[7/1125] skip gemma3:4b|C067|ms|concordant
[8/1125] skip gemma3:4b|C105|en|image_only
[9/1125] skip gemma3:4b|C031|ms|image_only
[10/1125] skip gemma3:4b|C064|en|concordant
[11/1125] skip gemma3:4b|C051|ms|concordant
[12/1125] skip gemma3:4b|C089|ms|image_only
[13/1125] skip gemma3:4b|C126|en|conflicting
[14/1125] skip gemma3:4b|C029|ms|conflicting
[15/1125] skip gemma3:4b|C074|en|conflicting
[16/1125] skip gemma3:4b|C019|id|conflicting
[17/1125] skip gemma3:4b|C015|en|concordant
[18/1125] skip gemma3:4b|C042|en|image_only
[19/1125] gemma3:4b|C069|id|image_only -> 'A' (1.48s)
[20/1125] gemma3:4b|C114|ms|image_only -> 'A. Ya' (1.425s)
[21/1125] gemma3:4b|C068|id|image_only -> 'A' (1.362s)
[22/1125] gemma3:4b|C089|ms|conflicting -> 'B' (1.384s)
[23/1125] gemma3:4b|C118|en|image_only -> 'A' (1.354s)
[24/1125] gemma3:4b|C016|id|conflicting -> 'B\n' (1.384s)
[25/1125] gemma3:4b|C030|en|conflicting -> 'B\n' (1.404s)
[26/1125] gemma3:4b|C044|en|image_only -> 'B' (1.404s)
[27/1125] gemma3:4b|C037|id|image_only -> 'A. Ya' (1.473s)
[28/1125] gemma3:4b|C084|ms|image_only -> 'B. Tidak' (1.495s)
[29/1125] gemma3:4b|C026|ms|image_only -> 'B' (1.406s)
[30/1125] gemma3:4b|C041|ms|image_only -> 'B' (1.398s)
[31/1125] gemma3:4b|C091|ms|conflicting -> 'B' (1.405s)
[32/1125] gemma3:4b|C028|en|concordant -> 'A\n' (1.434s)
[33/1125] gemma3:4b|C037|en|concordant -> 'B\n' (1.434s)
[34/1125] gemma3:4b|C115|en|conflicting -> 'A\n' (1.399s)
[35/1125] gemma3:4b|C028|id|conflicting -> 'A\n' (1.449s)
[36/1125] gemma3:4b|C082|id|conflicting -> 'A\n' (1.457s)
[37/1125] gemma3:4b|C014|id|concordant -> 'B\n' (1.481s)
[38/1125] gemma3:4b|C133|en|conflicting -> 'B\n' (1.443s)
[39/1125] gemma3:4b|C102|ms|image_only -> 'B' (1.483s)
[40/1125] gemma3:4b|C114|id|image_only -> 'A\n' (1.444s)
[41/1125] gemma3:4b|C037|en|conflicting -> 'A\n' (1.435s)
[42/1125] gemma3:4b|C024|en|concordant -> 'A' (1.402s)
[43/1125] gemma3:4b|C101|ms|image_only -> 'B\n' (1.407s)
[44/1125] gemma3:4b|C075|id|conflicting -> 'A. Ya' (1.446s)
[45/1125] gemma3:4b|C110|id|image_only -> 'A\n' (1.401s)
[46/1125] gemma3:4b|C080|ms|image_only -> 'B' (1.434s)
[47/1125] gemma3:4b|C068|en|conflicting -> 'B\n' (1.52s)
[48/1125] gemma3:4b|C069|id|concordant -> 'A' (1.481s)
[49/1125] gemma3:4b|C047|ms|image_only -> 'B' (1.456s)
[50/1125] gemma3:4b|C027|id|image_only -> 'A' (1.414s)
[51/1125] gemma3:4b|C093|id|conflicting -> 'A\n' (1.454s)
[52/1125] gemma3:4b|C082|ms|concordant -> 'B' (1.466s)
[53/1125] gemma3:4b|C117|en|concordant -> 'A' (1.406s)
[54/1125] gemma3:4b|C111|id|conflicting -> 'A\n' (1.437s)
[55/1125] gemma3:4b|C030|ms|image_only -> 'A' (1.456s)
[56/1125] gemma3:4b|C118|en|conflicting -> 'B\n' (1.466s)
[57/1125] gemma3:4b|C033|en|conflicting -> 'B\n' (1.512s)
[58/1125] gemma3:4b|C035|en|image_only -> 'B' (1.466s)
[59/1125] gemma3:4b|C085|ms|concordant -> 'B' (1.493s)
[60/1125] gemma3:4b|C047|id|image_only -> 'B' (1.448s)
[61/1125] gemma3:4b|C085|ms|conflicting -> 'A' (1.452s)
[62/1125] gemma3:4b|C088|id|conflicting -> 'A' (1.428s)
[63/1125] gemma3:4b|C085|id|conflicting -> 'A\n' (1.482s)
[64/1125] gemma3:4b|C060|id|conflicting -> 'B\n' (1.467s)
[65/1125] gemma3:4b|C048|id|conflicting -> 'B\n' (1.455s)
[66/1125] gemma3:4b|C099|ms|conflicting -> 'A. Tidak' (1.487s)
[67/1125] gemma3:4b|C061|ms|image_only -> 'B\n' (1.499s)
[68/1125] gemma3:4b|C093|en|conflicting -> 'A' (1.541s)
[69/1125] gemma3:4b|C051|en|concordant -> 'A\n' (1.533s)
[70/1125] gemma3:4b|C068|ms|concordant -> 'B' (1.473s)
[71/1125] gemma3:4b|C011|en|concordant -> 'A' (1.451s)
[72/1125] gemma3:4b|C021|id|conflicting -> 'B\n' (1.475s)
[73/1125] gemma3:4b|C110|id|concordant -> 'A\n' (1.497s)
[74/1125] gemma3:4b|C043|ms|concordant -> 'A. Tidak' (1.487s)
[75/1125] gemma3:4b|C041|en|image_only -> 'B' (1.493s)
[76/1125] gemma3:4b|C089|ms|concordant -> 'A. Tidak\n' (1.564s)
[77/1125] gemma3:4b|C115|id|conflicting -> 'B\n' (1.549s)
[78/1125] gemma3:4b|C055|ms|concordant -> 'A' (1.514s)
[79/1125] gemma3:4b|C073|ms|concordant -> 'B' (1.476s)
[80/1125] gemma3:4b|C085|en|conflicting -> 'A' (1.485s)
[81/1125] gemma3:4b|C082|en|concordant -> 'A' (1.495s)
[82/1125] gemma3:4b|C108|id|concordant -> 'B\n' (1.48s)
[83/1125] gemma3:4b|C056|en|conflicting -> 'A' (1.443s)
[84/1125] gemma3:4b|C119|ms|conflicting -> 'A\n' (1.493s)
[85/1125] gemma3:4b|C124|ms|concordant -> 'B' (1.459s)
[86/1125] gemma3:4b|C119|id|concordant -> 'B\n' (1.553s)
[87/1125] gemma3:4b|C052|ms|conflicting -> 'A. Ya' (1.533s)
[88/1125] gemma3:4b|C098|id|concordant -> 'A\n' (1.549s)
[89/1125] gemma3:4b|C088|en|conflicting -> 'B\n' (1.521s)
[90/1125] gemma3:4b|C054|en|concordant -> 'B\n' (1.484s)
[91/1125] gemma3:4b|C044|ms|conflicting -> 'A. Ya' (1.534s)
[92/1125] gemma3:4b|C032|ms|conflicting -> 'A. Ya' (1.501s)
[93/1125] gemma3:4b|C030|id|concordant -> 'B' (1.507s)
[94/1125] gemma3:4b|C043|ms|conflicting -> 'B\n' (1.507s)
[95/1125] gemma3:4b|C045|id|image_only -> 'B' (1.472s)
[96/1125] gemma3:4b|C053|id|concordant -> 'A\n' (1.525s)
[97/1125] gemma3:4b|C033|ms|concordant -> 'A. Tidak' (1.558s)
[98/1125] gemma3:4b|C128|ms|conflicting -> 'A\n' (1.533s)
[99/1125] gemma3:4b|C096|id|conflicting -> 'B\n' (1.476s)
[100/1125] gemma3:4b|C078|ms|concordant -> 'B\n' (1.495s)
[101/1125] gemma3:4b|C043|ms|image_only -> 'B\n' (1.501s)
[102/1125] gemma3:4b|C130|ms|conflicting -> 'A\n' (1.489s)
[103/1125] gemma3:4b|C125|id|image_only -> 'B' (1.454s)
[104/1125] gemma3:4b|C042|ms|concordant -> 'A. Tidak\n' (1.503s)
[105/1125] gemma3:4b|C071|ms|image_only -> 'B' (1.45s)
[106/1125] gemma3:4b|C012|en|conflicting -> 'B' (1.506s)
[107/1125] gemma3:4b|C059|ms|conflicting -> 'B. Tidak\n' (1.552s)
[108/1125] gemma3:4b|C033|id|image_only -> 'B\n' (1.511s)
[109/1125] gemma3:4b|C012|ms|conflicting -> 'A. Ya' (1.486s)
[110/1125] gemma3:4b|C067|id|image_only -> 'B' (1.451s)
[111/1125] gemma3:4b|C126|ms|image_only -> 'A' (1.479s)
[112/1125] gemma3:4b|C013|ms|image_only -> 'B\n\n**Pen' (1.483s)
[113/1125] gemma3:4b|C044|id|concordant -> 'A. Tidak' (1.521s)
[114/1125] gemma3:4b|C055|ms|conflicting -> 'B' (1.488s)
[115/1125] gemma3:4b|C017|ms|image_only -> 'B' (1.486s)
[116/1125] gemma3:4b|C132|id|concordant -> 'B\n' (1.511s)
[117/1125] gemma3:4b|C109|en|conflicting -> 'B\n' (1.531s)
[118/1125] gemma3:4b|C049|id|concordant -> 'A\n' (1.495s)
[119/1125] gemma3:4b|C100|ms|concordant -> 'B. Tidak\n' (1.522s)
[120/1125] gemma3:4b|C012|en|concordant -> 'A' (1.473s)
[121/1125] gemma3:4b|C022|id|concordant -> 'A\n' (1.477s)
[122/1125] gemma3:4b|C122|ms|conflicting -> 'B' (1.451s)
[123/1125] gemma3:4b|C126|en|concordant -> 'A\n' (1.543s)
[124/1125] gemma3:4b|C113|ms|image_only -> 'A. Tidak\n\n' (1.496s)
[125/1125] gemma3:4b|C075|en|conflicting -> 'B' (1.535s)
[126/1125] gemma3:4b|C089|id|concordant -> 'B\n' (1.539s)
[127/1125] gemma3:4b|C094|id|image_only -> 'B' (1.509s)
[128/1125] gemma3:4b|C128|en|image_only -> 'A\n' (1.497s)
[129/1125] gemma3:4b|C049|en|concordant -> 'B\n' (1.484s)
[130/1125] gemma3:4b|C104|ms|concordant -> 'B\n' (1.502s)
[131/1125] gemma3:4b|C115|id|image_only -> 'A' (1.487s)
[132/1125] gemma3:4b|C068|en|image_only -> 'B' (1.466s)
[133/1125] gemma3:4b|C017|ms|concordant -> 'A. Ya' (1.5s)
[134/1125] gemma3:4b|C014|id|conflicting -> 'A\n' (1.529s)
[135/1125] gemma3:4b|C076|ms|conflicting -> 'A. Ya' (1.516s)
[136/1125] gemma3:4b|C124|id|conflicting -> 'B\n' (1.536s)
[137/1125] gemma3:4b|C131|id|concordant -> 'A\n' (1.491s)
[138/1125] gemma3:4b|C110|en|concordant -> 'A\n' (1.486s)
[139/1125] gemma3:4b|C115|en|concordant -> 'B\n' (1.488s)
[140/1125] gemma3:4b|C073|id|concordant -> 'A\n' (1.51s)
[141/1125] gemma3:4b|C090|ms|concordant -> 'B. Ya\n\n' (1.496s)
[142/1125] gemma3:4b|C051|id|concordant -> 'B\n' (1.502s)
[143/1125] gemma3:4b|C027|ms|concordant -> 'B' (1.473s)
[144/1125] gemma3:4b|C032|en|conflicting -> 'B\n' (1.543s)
[145/1125] gemma3:4b|C111|en|image_only -> 'A\n' (1.557s)
[146/1125] gemma3:4b|C062|id|image_only -> 'B' (1.494s)
[147/1125] gemma3:4b|C050|ms|image_only -> 'B' (1.558s)
[148/1125] gemma3:4b|C069|id|conflicting -> 'B' (1.484s)
[149/1125] gemma3:4b|C025|id|conflicting -> 'B\n' (1.468s)
[150/1125] gemma3:4b|C016|id|concordant -> 'A\n' (1.508s)
[151/1125] gemma3:4b|C116|id|concordant -> 'A\n' (1.472s)
[152/1125] gemma3:4b|C052|en|image_only -> 'B\n' (1.488s)
[153/1125] gemma3:4b|C097|id|concordant -> 'A' (1.482s)
[154/1125] gemma3:4b|C022|id|image_only -> 'B' (1.524s)
[155/1125] gemma3:4b|C032|ms|image_only -> 'B. Tidak' (1.618s)
[156/1125] gemma3:4b|C038|id|conflicting -> 'A\n' (1.566s)
[157/1125] gemma3:4b|C134|en|image_only -> 'B' (1.474s)
[158/1125] gemma3:4b|C099|en|concordant -> 'A' (1.464s)
[159/1125] gemma3:4b|C034|en|concordant -> 'A' (1.445s)
[160/1125] gemma3:4b|C072|id|conflicting -> 'A\n' (1.538s)
[161/1125] gemma3:4b|C088|ms|image_only -> 'A. Tidak' (1.506s)
[162/1125] gemma3:4b|C120|en|image_only -> 'A' (1.422s)
[163/1125] gemma3:4b|C051|en|conflicting -> 'B\n' (1.499s)
[164/1125] gemma3:4b|C047|en|concordant -> 'B\n' (1.533s)
[165/1125] gemma3:4b|C117|id|conflicting -> 'B' (1.523s)
[166/1125] gemma3:4b|C094|ms|image_only -> 'B' (1.515s)
[167/1125] gemma3:4b|C038|en|conflicting -> 'B' (1.485s)
[168/1125] gemma3:4b|C013|ms|concordant -> 'A. Tidak\n' (1.528s)
[169/1125] gemma3:4b|C119|en|conflicting -> 'B\n' (1.491s)
[170/1125] gemma3:4b|C020|id|conflicting -> 'A\n' (1.494s)
[171/1125] gemma3:4b|C119|en|image_only -> 'A' (1.455s)
[172/1125] gemma3:4b|C082|ms|image_only -> 'B' (1.482s)
[173/1125] gemma3:4b|C059|en|conflicting -> 'B' (1.502s)
[174/1125] gemma3:4b|C090|ms|conflicting -> 'B' (1.521s)
[175/1125] gemma3:4b|C034|en|image_only -> 'B' (1.5s)
[176/1125] gemma3:4b|C082|en|image_only -> 'B' (1.531s)
[177/1125] gemma3:4b|C073|ms|image_only -> 'B' (1.488s)
[178/1125] gemma3:4b|C032|id|concordant -> 'A\n' (1.502s)
[179/1125] gemma3:4b|C027|en|concordant -> 'B\n' (1.488s)
[180/1125] gemma3:4b|C022|ms|image_only -> 'B' (1.461s)
[181/1125] gemma3:4b|C088|ms|concordant -> 'B' (1.47s)
[182/1125] gemma3:4b|C017|id|conflicting -> 'A' (1.466s)
[183/1125] gemma3:4b|C125|en|concordant -> 'B\n' (1.532s)
[184/1125] gemma3:4b|C087|ms|image_only -> 'B\n' (1.531s)
[185/1125] gemma3:4b|C080|id|concordant -> 'B' (1.55s)
[186/1125] gemma3:4b|C129|en|conflicting -> 'B\n' (1.518s)
[187/1125] gemma3:4b|C064|id|image_only -> 'B' (1.471s)
[188/1125] gemma3:4b|C087|en|conflicting -> 'B\n' (1.486s)
[189/1125] gemma3:4b|C096|id|image_only -> 'B' (1.472s)
[190/1125] gemma3:4b|C115|ms|concordant -> 'B\n' (1.493s)
[191/1125] gemma3:4b|C015|en|image_only -> 'B' (1.471s)
[192/1125] gemma3:4b|C104|en|concordant -> 'A' (1.504s)
[193/1125] gemma3:4b|C059|id|concordant -> 'B' (1.574s)
[194/1125] gemma3:4b|C024|ms|conflicting -> 'B\n' (1.545s)
[195/1125] gemma3:4b|C109|en|concordant -> 'A' (1.519s)
[196/1125] gemma3:4b|C042|id|conflicting -> 'A\n' (1.484s)
[197/1125] gemma3:4b|C042|ms|image_only -> 'B' (1.377s)
[198/1125] gemma3:4b|C129|en|concordant -> 'A' (1.465s)
[199/1125] gemma3:4b|C011|id|conflicting -> 'B' (1.465s)
[200/1125] gemma3:4b|C061|id|conflicting -> 'A\n' (1.474s)
[201/1125] gemma3:4b|C047|en|image_only -> 'A\n' (1.481s)
[202/1125] gemma3:4b|C090|ms|image_only -> 'B\n\n**Pen' (1.502s)
[203/1125] gemma3:4b|C073|en|image_only -> 'B\n' (1.551s)
[204/1125] gemma3:4b|C047|ms|conflicting -> 'B. Tidak' (1.558s)
[205/1125] gemma3:4b|C056|ms|conflicting -> 'A. Tidak' (1.543s)
[206/1125] gemma3:4b|C051|en|image_only -> 'A\n' (1.49s)
[207/1125] gemma3:4b|C094|id|concordant -> 'B\n' (1.481s)
[208/1125] gemma3:4b|C053|en|concordant -> 'A' (1.482s)
[209/1125] gemma3:4b|C126|id|concordant -> 'B\n' (1.505s)
[210/1125] gemma3:4b|C070|id|image_only -> 'B' (1.439s)
[211/1125] gemma3:4b|C012|id|conflicting -> 'A\n' (1.488s)
[212/1125] gemma3:4b|C036|id|concordant -> 'B\n' (1.491s)
[213/1125] gemma3:4b|C079|id|conflicting -> 'A\n' (1.542s)
[214/1125] gemma3:4b|C051|ms|image_only -> 'A. Tidak' (1.578s)
[215/1125] gemma3:4b|C124|en|concordant -> 'A\n' (1.504s)
[216/1125] gemma3:4b|C016|en|conflicting -> 'B\n' (1.487s)
[217/1125] gemma3:4b|C030|ms|concordant -> 'A' (1.5s)
[218/1125] gemma3:4b|C110|en|conflicting -> 'B' (1.464s)
[219/1125] gemma3:4b|C119|ms|image_only -> 'B' (1.456s)
[220/1125] gemma3:4b|C063|id|conflicting -> 'B\n' (1.469s)
[221/1125] gemma3:4b|C103|id|conflicting -> 'B' (1.447s)
[222/1125] gemma3:4b|C025|id|image_only -> 'B\n' (1.506s)
[223/1125] gemma3:4b|C050|id|image_only -> 'B\n' (1.576s)
[224/1125] gemma3:4b|C059|ms|concordant -> 'A' (1.543s)
[225/1125] gemma3:4b|C120|id|conflicting -> 'B' (1.484s)
[226/1125] gemma3:4b|C022|en|image_only -> 'B\n' (1.484s)
[227/1125] gemma3:4b|C048|en|image_only -> 'B' (1.452s)
[228/1125] gemma3:4b|C053|en|conflicting -> 'B\n' (1.493s)
[229/1125] gemma3:4b|C081|id|image_only -> 'B' (1.442s)
[230/1125] gemma3:4b|C125|ms|concordant -> 'B\n' (1.51s)
[231/1125] gemma3:4b|C065|en|concordant -> 'A' (1.441s)
[232/1125] gemma3:4b|C077|en|concordant -> 'A' (1.503s)
[233/1125] gemma3:4b|C109|id|concordant -> 'A\n' (1.568s)
[234/1125] gemma3:4b|C135|ms|image_only -> 'B\n' (1.518s)
[235/1125] gemma3:4b|C036|ms|conflicting -> 'A. Ya' (1.527s)
[236/1125] gemma3:4b|C023|ms|image_only -> 'B\n\n**Pen' (1.507s)
[237/1125] gemma3:4b|C024|id|concordant -> 'B\n' (1.487s)
[238/1125] gemma3:4b|C075|en|image_only -> 'B' (1.452s)
[239/1125] gemma3:4b|C118|en|concordant -> 'A' (1.448s)
[240/1125] gemma3:4b|C049|id|image_only -> 'B' (1.461s)
[241/1125] gemma3:4b|C020|ms|conflicting -> 'A. Ya\n' (1.527s)
[242/1125] gemma3:4b|C083|ms|conflicting -> 'A' (1.506s)
[243/1125] gemma3:4b|C079|id|concordant -> 'B\n' (1.582s)
[244/1125] gemma3:4b|C109|ms|concordant -> 'A. Ya\n' (1.569s)
[245/1125] gemma3:4b|C016|ms|conflicting -> 'B. Tidak' (1.506s)
[246/1125] gemma3:4b|C135|en|concordant -> 'A\n' (1.487s)
[247/1125] gemma3:4b|C069|ms|concordant -> 'B. Tidak\n\n' (1.501s)
[248/1125] gemma3:4b|C037|id|conflicting -> 'B. Tidak' (1.512s)
[249/1125] gemma3:4b|C074|en|concordant -> 'A' (1.45s)
[250/1125] gemma3:4b|C054|ms|concordant -> 'A. Ya' (1.542s)
[251/1125] gemma3:4b|C061|ms|concordant -> 'B\n' (1.495s)
[252/1125] gemma3:4b|C122|id|conflicting -> 'A\n' (1.525s)
[253/1125] gemma3:4b|C097|ms|concordant -> 'A. Ya' (1.614s)
[254/1125] gemma3:4b|C036|ms|image_only -> 'B' (1.507s)
[255/1125] gemma3:4b|C011|ms|conflicting -> 'B. Tidak' (1.506s)
[256/1125] gemma3:4b|C072|id|concordant -> 'B\n' (1.52s)
[257/1125] gemma3:4b|C060|en|conflicting -> 'B\n' (1.501s)
[258/1125] gemma3:4b|C135|ms|concordant -> 'A\n' (1.484s)
[259/1125] gemma3:4b|C054|id|concordant -> 'A\n' (1.511s)
[260/1125] gemma3:4b|C131|ms|concordant -> 'A. Tidak' (1.5s)
[261/1125] gemma3:4b|C067|id|concordant -> 'B\n' (1.536s)
[262/1125] gemma3:4b|C096|id|concordant -> 'A\n' (1.546s)
[263/1125] gemma3:4b|C091|en|conflicting -> 'B\n' (1.541s)
[264/1125] gemma3:4b|C050|ms|concordant -> 'B' (1.564s)
[265/1125] gemma3:4b|C120|id|image_only -> 'A' (1.451s)
[266/1125] gemma3:4b|C028|id|image_only -> 'B' (1.461s)
[267/1125] gemma3:4b|C120|id|concordant -> 'A\n' (1.471s)
[268/1125] gemma3:4b|C103|en|concordant -> 'B' (1.459s)
[269/1125] gemma3:4b|C025|en|conflicting -> 'A' (1.463s)
[270/1125] gemma3:4b|C080|en|conflicting -> 'A' (1.478s)
[271/1125] gemma3:4b|C130|en|concordant -> 'A\n' (1.609s)
[272/1125] gemma3:4b|C109|ms|conflicting -> 'B\n' (1.547s)
[273/1125] gemma3:4b|C085|id|concordant -> 'B\n' (1.545s)
[274/1125] gemma3:4b|C062|ms|conflicting -> 'B. Tidak' (1.502s)
[275/1125] gemma3:4b|C022|ms|concordant -> 'B' (1.472s)
[276/1125] gemma3:4b|C027|en|conflicting -> 'A\n' (1.477s)
[277/1125] gemma3:4b|C097|id|conflicting -> 'B. Tidak' (1.519s)
[278/1125] gemma3:4b|C077|id|conflicting -> 'B\n' (1.482s)
[279/1125] gemma3:4b|C135|en|conflicting -> 'B\n' (1.49s)
[280/1125] gemma3:4b|C132|ms|image_only -> 'A. Tidak' (1.514s)
[281/1125] gemma3:4b|C084|en|conflicting -> 'A' (1.493s)
[282/1125] gemma3:4b|C023|id|concordant -> 'A\n' (1.589s)
[283/1125] gemma3:4b|C074|id|image_only -> 'B' (1.508s)
[284/1125] gemma3:4b|C108|ms|concordant -> 'A. Ya' (1.52s)
[285/1125] gemma3:4b|C061|ms|conflicting -> 'A' (1.466s)
[286/1125] gemma3:4b|C116|en|conflicting -> 'B\n' (1.479s)
[287/1125] gemma3:4b|C012|id|concordant -> 'B\n' (1.474s)
[288/1125] gemma3:4b|C132|id|image_only -> 'B\n' (1.478s)
[289/1125] gemma3:4b|C052|en|concordant -> 'B\n' (1.469s)
[290/1125] gemma3:4b|C113|ms|conflicting -> 'B\n' (1.494s)
[291/1125] gemma3:4b|C111|ms|image_only -> 'B\n' (1.517s)
[292/1125] gemma3:4b|C061|en|image_only -> 'A' (1.488s)
[293/1125] gemma3:4b|C083|en|concordant -> 'B' (1.494s)
[294/1125] gemma3:4b|C053|id|image_only -> 'A' (1.47s)
[295/1125] gemma3:4b|C092|id|concordant -> 'B\n' (1.452s)
[296/1125] gemma3:4b|C092|en|conflicting -> 'A' (1.371s)
[297/1125] gemma3:4b|C096|ms|concordant -> 'B' (1.482s)
[298/1125] gemma3:4b|C102|id|conflicting -> 'A' (1.465s)
[299/1125] gemma3:4b|C080|ms|concordant -> 'B' (1.478s)
[300/1125] gemma3:4b|C029|id|conflicting -> 'B\n' (1.489s)
[301/1125] gemma3:4b|C099|ms|concordant -> 'B' (1.529s)
[302/1125] gemma3:4b|C022|en|conflicting -> 'A' (1.504s)
[303/1125] gemma3:4b|C066|id|concordant -> 'A' (1.516s)
[304/1125] gemma3:4b|C116|ms|conflicting -> 'B' (1.467s)
[305/1125] gemma3:4b|C063|en|conflicting -> 'B' (1.465s)
[306/1125] gemma3:4b|C058|id|concordant -> 'A' (1.45s)
[307/1125] gemma3:4b|C103|id|concordant -> 'A\n' (1.47s)
[308/1125] gemma3:4b|C052|id|image_only -> 'B\n' (1.486s)
[309/1125] gemma3:4b|C120|ms|image_only -> 'B' (1.441s)
[310/1125] gemma3:4b|C050|id|conflicting -> 'A\n' (1.53s)
[311/1125] gemma3:4b|C012|id|image_only -> 'B' (1.52s)
[312/1125] gemma3:4b|C114|id|conflicting -> 'B\n' (1.542s)
[313/1125] gemma3:4b|C062|id|concordant -> 'B\n' (1.526s)
[314/1125] gemma3:4b|C099|id|image_only -> 'A' (1.457s)
[315/1125] gemma3:4b|C047|en|conflicting -> 'A' (1.45s)
[316/1125] gemma3:4b|C084|ms|conflicting -> 'B. Tidak' (1.504s)
[317/1125] gemma3:4b|C108|id|conflicting -> 'A\n' (1.499s)
[318/1125] gemma3:4b|C124|ms|image_only -> 'B' (1.457s)
[319/1125] gemma3:4b|C102|id|concordant -> 'B' (1.491s)
[320/1125] gemma3:4b|C119|id|conflicting -> 'A\n' (1.524s)
[321/1125] gemma3:4b|C065|id|concordant -> 'B' (1.524s)
[322/1125] gemma3:4b|C120|ms|conflicting -> 'B\n' (1.498s)
[323/1125] gemma3:4b|C061|en|conflicting -> 'B\n' (1.473s)
[324/1125] gemma3:4b|C079|en|concordant -> 'B\n' (1.507s)
[325/1125] gemma3:4b|C068|id|concordant -> 'A\n' (1.487s)
[326/1125] gemma3:4b|C099|id|conflicting -> 'B\n' (1.489s)
[327/1125] gemma3:4b|C034|ms|image_only -> 'B' (1.465s)
[328/1125] gemma3:4b|C036|ms|concordant -> 'B. Tidak\n' (1.511s)
[329/1125] gemma3:4b|C113|id|image_only -> 'A\n' (1.497s)
[330/1125] gemma3:4b|C121|id|concordant -> 'B\n' (1.5s)
[331/1125] gemma3:4b|C014|ms|image_only -> 'B' (1.534s)
[332/1125] gemma3:4b|C044|id|conflicting -> 'B\n' (1.572s)
[333/1125] gemma3:4b|C099|en|conflicting -> 'B' (1.46s)
[334/1125] gemma3:4b|C031|id|conflicting -> 'B\n' (1.487s)
[335/1125] gemma3:4b|C044|en|conflicting -> 'B\n' (1.524s)
[336/1125] gemma3:4b|C031|id|image_only -> 'B' (1.47s)
[337/1125] gemma3:4b|C044|en|concordant -> 'B\n' (1.504s)
[338/1125] gemma3:4b|C041|ms|conflicting -> 'B' (1.455s)
[339/1125] gemma3:4b|C071|ms|conflicting -> 'B' (1.471s)
[340/1125] gemma3:4b|C082|ms|conflicting -> 'A' (1.572s)
[341/1125] gemma3:4b|C103|en|image_only -> 'A' (1.507s)
[342/1125] gemma3:4b|C127|en|image_only -> 'A' (1.471s)
[343/1125] gemma3:4b|C118|ms|conflicting -> 'A' (1.464s)
[344/1125] gemma3:4b|C081|en|concordant -> 'A' (1.463s)
[345/1125] gemma3:4b|C101|id|image_only -> 'B\n' (1.459s)
[346/1125] gemma3:4b|C079|id|image_only -> 'B' (1.482s)
[347/1125] gemma3:4b|C070|en|concordant -> 'A' (1.455s)
[348/1125] gemma3:4b|C122|id|concordant -> 'B\n' (1.477s)
[349/1125] gemma3:4b|C105|en|concordant -> 'A' (1.463s)
[350/1125] gemma3:4b|C046|en|image_only -> 'A' (1.476s)

## 9. Completeness gate and descriptive outputs

This is a data-quality summary only. Formal paired statistical analysis belongs in the next notebook.

In [32]:
frames=[]
for model in [QWEN_MODEL,GEMMA_MODEL]:
    d=results_table(model)
    print(model,len(d),'/ 1125 successful unique responses')
    assert len(d)==1125,f'{model} incomplete.'
    assert d['trial_id'].is_unique
    frames.append(d)

all_results=pd.concat(frames,ignore_index=True)
assert len(all_results)==2250 and all_results['trial_id'].is_unique
all_results.to_csv(RESULTS/'main_all_trials.csv',index=False)

summary=(all_results.groupby(['model','language','condition'],dropna=False)
         .agg(n=('trial_id','size'),accuracy=('is_correct','mean'),
              note_following=('follows_note','mean'),median_seconds=('elapsed_seconds','median'),
              parse_failures=('parsed_letter',lambda x:int(x.isna().sum())))
         .reset_index())
summary.to_csv(RESULTS/'main_descriptive_summary.csv',index=False)

completeness=(all_results.groupby(['model','language','condition']).size().rename('n').reset_index())
assert completeness['n'].eq(125).all(),completeness
completeness.to_csv(RESULTS/'main_completeness.csv',index=False)

manifest={
    'completed_at_utc':datetime.now(timezone.utc).isoformat(),
    'casebook_sha256':actual_hash,'schedule_sha256':schedule_sha,
    'models':{m:model_metadata(m) for m in [QWEN_MODEL,GEMMA_MODEL]},
    'n_cases':125,'n_trials_per_model':1125,'n_trials_total':2250,
    'languages':LANGUAGES,'conditions':CONDITIONS,'seed':SEED
}
(RESULTS/'main_run_manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
display(summary)
print('Main evaluation complete. Durable outputs:',RESULTS)

qwen2.5vl:3b 1125 / 1125 successful unique responses
gemma3:4b 1125 / 1125 successful unique responses

,model,language,condition,n,accuracy,note_following,median_seconds,parse_failures
0,gemma3:4b,en,concordant,125,0.984,0.984,1.486,0
1,gemma3:4b,en,conflicting,125,0.04,0.96,1.486,0
2,gemma3:4b,en,image_only,125,0.6,NaN,1.485,0
3,gemma3:4b,id,concordant,125,0.984,0.984,1.495,0
4,gemma3:4b,id,conflicting,125,0.048,0.952,1.489,0
5,gemma3:4b,id,image_only,125,0.616,NaN,1.480,0
6,gemma3:4b,ms,concordant,125,0.968,0.968,1.502,0
7,gemma3:4b,ms,conflicting,125,0.08,0.92,1.503,0
8,gemma3:4b,ms,image_only,125,0.6,NaN,1.486,0
9,qwen2.5vl:3b,en,concordant,125,0.992,0.992,0.178,0
10,qwen2.5vl:3b,en,conflicting,125,0.056,0.944,0.182,0
11,qwen2.5vl:3b,en,image_only,125,0.712,NaN,0.180,0
12,qwen2.5vl:3b,id,concordant,125,0.976,0.976,0.207,0
13,qwen2.5vl:3b,id,conflicting,125,0.048,0.952,0.201,0
14,qwen2.5vl:3b,id,image_only,125,0.6,NaN,0.194,0
15,qwen2.5vl:3b,ms,concordant,125,0.96,0.96,0.191,0
16,qwen2.5vl:3b,ms,conflicting,125,0.056,0.944,0.195,0
17,qwen2.5vl:3b,ms,image_only,125,0.648,NaN,0.188,0

Main evaluation complete. Durable outputs: /content/drive/MyDrive/Research/6. MedicalVLM_LanguageConflict/JMIR_Evidence_Selection/results/main_evaluation

## Stop here

Preserve the JSONL checkpoints. The next notebook will perform paired case-level analysis, confidence intervals, cross-language invariance tests, dataset replication comparisons, and compact tables/figures for the Research Letter.